version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./:/go/src/github.com/reco-pool
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reco-pool
    ports:
      - 5432:5432
